/****************************************************************************
 *
 *   Copyright (c) 2026 PX4 Development Team. All rights reserved.
 *
 ****************************************************************************/

/**
 * Select multicopter position outer-loop controller
 *
 * 0: use the original PX4 position P plus velocity PID controller
 * 1: retired, falls back to PID for safety
 * 2: use second-order LADRC with position, velocity and disturbance ESO states
 * on all axes
 * 3: use second-order LADRC on X/Y and the original PX4 PID on Z
 *
 * @min 0
 * @max 3
 * @value 0 PID
 * @value 1 Retired_PID
 * @value 2 LADRC2
 * @value 3 LADRC2XY_PIDZ
 * @group Multicopter Position Control
 */
PARAM_DEFINE_INT32(MC_PLADRC_EN, 0);

/**
 * Position LADRC horizontal equivalent input gain
 *
 * Nominal b0 for X/Y axes in: velocity_dot = disturbance + b0 * acceleration.
 *
 * @min 0.001
 * @max 10
 * @decimal 3
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_B0_XY, 1.0f);

/**
 * Position LADRC vertical equivalent input gain
 *
 * Nominal b0 for Z axis in: velocity_dot = disturbance + b0 * acceleration.
 *
 * @min 0.001
 * @max 10
 * @decimal 3
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_B0_Z, 1.0f);

/**
 * Position LADRC horizontal controller bandwidth
 *
 * Higher value gives faster horizontal velocity tracking.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_WC_XY, 1.8f);

/**
 * Position LADRC vertical controller bandwidth
 *
 * Higher value gives faster vertical velocity tracking.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_WC_Z, 4.0f);

/**
 * Position LADRC horizontal observer bandwidth
 *
 * Higher value gives faster disturbance estimation, but increases velocity
 * noise sensitivity.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_WO_XY, 6.0f);

/**
 * Position LADRC vertical observer bandwidth
 *
 * Higher value gives faster disturbance estimation, but increases velocity
 * noise sensitivity.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_WO_Z, 10.0f);

/**
 * Position LADRC horizontal acceleration limit
 *
 * Maximum horizontal acceleration correction generated by LADRC.
 *
 * @unit m/s^2
 * @min 0.001
 * @max 50
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_LIM_XY, 3.0f);

/**
 * Position LADRC upward acceleration limit
 *
 * Maximum upward acceleration correction generated by LADRC. PX4 uses NED
 * coordinates, so upward acceleration is negative Z internally.
 *
 * @unit m/s^2
 * @min 0.001
 * @max 50
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_LIM_UP, 3.0f);

/**
 * Position LADRC downward acceleration limit
 *
 * Maximum downward acceleration correction generated by LADRC.
 *
 * @unit m/s^2
 * @min 0.001
 * @max 50
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_LIM_DN, 2.0f);

/**
 * Position LADRC horizontal acceleration damping
 *
 * Optional damping applied as -gain * measured horizontal acceleration on top
 * of the LADRC command.
 *
 * @min 0
 * @max 10
 * @decimal 3
 * @increment 0.01
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_D_XY, 0.0f);

/**
 * Position LADRC vertical acceleration damping
 *
 * Optional damping applied as -gain * measured vertical acceleration on top
 * of the LADRC command.
 *
 * @min 0
 * @max 10
 * @decimal 3
 * @increment 0.01
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_D_Z, 0.0f);

/**
 * Position LADRC horizontal EKF velocity feedback weight
 *
 * Blends the second-order LESO velocity state z2 with the estimator velocity
 * in the horizontal nominal velocity-feedback term. Zero preserves the
 * original z2-only controller. Invalid estimator velocity automatically
 * falls back to z2.
 *
 * @min 0
 * @max 1
 * @decimal 2
 * @increment 0.05
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_VFB_W, 0.0f);

/**
 * Position LADRC TD enable
 *
 * Enables the tracking differentiator that shapes the velocity setpoint input
 * of the position LADRC.
 *
 * @boolean
 * @group Multicopter Position Control
 */
PARAM_DEFINE_INT32(MC_PLADRC_TD_EN, 1);

/**
 * Position LADRC TD horizontal bandwidth
 *
 * Bandwidth for the X/Y velocity setpoint tracking differentiator.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_TD_WXY, 2.0f);

/**
 * Position LADRC TD vertical bandwidth
 *
 * Bandwidth for the Z velocity setpoint tracking differentiator.
 *
 * @min 0.01
 * @max 100
 * @unit rad/s
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_TD_WZ, 3.0f);

/**
 * Position LADRC TD horizontal acceleration limit
 *
 * Maximum rate of change for the shaped X/Y velocity setpoint.
 *
 * @unit m/s^2
 * @min 0.001
 * @max 50
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_TD_AXY, 2.0f);

/**
 * Position LADRC TD vertical acceleration limit
 *
 * Maximum rate of change for the shaped Z velocity setpoint.
 *
 * @unit m/s^2
 * @min 0.001
 * @max 50
 * @decimal 2
 * @increment 0.1
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_TD_AZ, 2.0f);

/**
 * Position LADRC TD damping ratio
 *
 * Damping ratio for the second-order tracking differentiator.
 *
 * @min 0.5
 * @max 2.0
 * @decimal 2
 * @increment 0.05
 * @group Multicopter Position Control
 */
PARAM_DEFINE_FLOAT(MC_PLADRC_TD_DMP, 1.0f);
